name: Share data between jobs

on: [push]

jobs:
  upload:
    name: Upload cat
    runs-on: ubuntu-latest
    steps:
      - name: Upload cat.png
        uses: actions/upload-artifact@v3
        with:
          name: cat
          path: cat.png
          
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: my_file.txt
          retention-days: 5
          
  download:
    name: Download cat
    runs-on: self-hosted
    steps:
      - name: Download math result for job 2
        uses: actions/download-artifact@v3
        with:
          name: homework
      - name: Print the final result
        shell: bash
        run: |
          cd C:\Users\TA-19E-118\Desktop\www
